[DRAFT] 91 binary datasets
alan-turing-institute/ARC-LoCoMoSeT pull request #97
Opened 2023-12-12 15:52 UTC by eddableheath

This pull request adds:

- Generation of binary classification datasets from the `visual_genome` object detection dataset from a CLI taking config file as input.
- Corresponding config file.

Todo:

- [ ] Tests.

2024-01-24 14:39 UTC, jack89roberts commented
Small initial comment but could you add something to the readme about how to use the dataset generation commands etc.?

2024-01-24 14:44 UTC, jack89roberts commented
Also add a readme to the `jan_24_configs` dir to briefly explain what they were used for.

2024-01-25 16:13 UTC, jack89roberts requested changes
Few small/documentation comments above but otherwise looks good to me. I reckon it could be made faster, e.g.

- The map with `convert_to_bin_classification` and then `get_balanced_id` means two iterations over the dataset, which probably could be reduced to one (partial) pass through the dataset.
- The for loop in `get_balanced_id` maybe could be replaced with some `datasets` filtering/sampling logic 

But don't think there's any need for us to try to optimise it further for now.

2024-01-25 16:13 UTC, jack89roberts commented on binary_dataset_generation.sh
Could this be put in a directory somewhere rather than at the top level, either in a new `scripts` directory or somewhere in the `locomoset` package, e.g. in the same place as `jobscript_template.sh`?

2024-01-25 16:13 UTC, jack89roberts commented on src/locomoset/config/config_classes.py
> +                )
Could this be replaced with a function, and then use that function in `test_init_fine_tuning_config` and `test_init_metric_config` so it's not repeated three times in the code?

2024-01-26 13:38 UTC, jack89roberts commented
Could we include the actual top level binary configs in this too (not just the template) @eddableheath (I couldn't find them from a quick browse at least)

2024-01-29 14:39 UTC, eddableheath commented on binary_dataset_generation.sh
I've moved it to `ARC-LoCoMoSeT/src/locomoset/config` alongside `jobscript_template.sh`.

2024-01-29 14:40 UTC, eddableheath commented
> Could we include the actual top level binary configs in this too (not just the template) @eddableheath (I couldn't find them from a quick browse at least)?

They were generated, and you'll find them on this branch on Baskerville. I'll put them into the configs on the git though.

2024-01-29 14:53 UTC, eddableheath commented on src/locomoset/config/config_classes.py
> +                )
I've replaced this with a function call.

2024-01-30 11:05 UTC, eddableheath commented
After a few git issues the binary dataset top level configs are now on the repo

2024-01-31 09:24 UTC, jack89roberts commented on src/locomoset/config/config_classes.py
> +                )
@eddableheath Could you use the new function in the tests as well? (`test_init_fine_tuning_config` and `test_init_metric_config `).

2024-01-31 09:30 UTC, jack89roberts commented on activate_condaenv.sh
Either remove this from the repo or move it to a sub-dir (I know it's my fault it exists in the first place, sorry...) If keeping it then lines 9 and 10 aren't needed in this file (`CONFIGSPATH` and `RUN_CALL` definitions, which are left over from the job submission templates but not needed just to load & activate the conda env).

2024-01-31 09:52 UTC, eddableheath commented on activate_condaenv.sh
Removed.

2024-01-31 09:56 UTC, eddableheath commented on src/locomoset/config/config_classes.py
> +                )
Done, somehow misread your original comment, sorry!

2024-01-31 10:51 UTC, jack89roberts approved these changes

2024-01-31 10:51 UTC, merged